# use 4,4 to make one to twenty

from math import *
print(" Hi everyone in IST 341")
print("Zero      is", int(4+4-4-4))
print("One       is", int(44/44))
print("Two       is", int(factorial(4)/4-sqrt(4)-sqrt(4)))
print("Three     is", int(sqrt(4)*sqrt(4)-4/4))
print("Four      is", int(4/4*sqrt(4)+sqrt(4)))
print("Five      is", int(4/4+sqrt(4)+sqrt(4)))
print("Six       is", int(4+sqrt(4)+4-4))
print("Seven     is", int(factorial(4)/4+4/4))
print("Eight     is", int(4+4+4-4))
print("Nine      is", int((factorial(4)-4)/4+4))
print("Ten       is", int(factorial(4)/4+sqrt(4)+sqrt(4)))
print("Eleven    is", int(factorial(4)/sqrt(4)-4/4))
print("Twelvn    is", int(factorial(4)-4-4-4))
print("Thirteen  is", int(44/4+sqrt(4)))
print("Fourteen  is", int(factorial(4)/sqrt(4)+4-sqrt(4)))
print("Fifteen   is", int(4*4-4/4))
print("Sixteen   is", int(4*4+4-4))
print("Seventeen is", int((4*4)+(4/4)))
print("Eighteen  is", int(factorial(4)-sqrt(4)-sqrt(4)-sqrt(4)))
print("Nineteen  is", int(factorial(4)-4-4/4))
print("Twenty    is", int(factorial(4)-4+4-4))